### ISSUE TITLE
对权限设计的疑问

### ISSUE THREAD

**Issue by ruixiu** [lenve/vhr#10]
假设有两个业务：教师管理、课程管理，分别对应：教师管理菜单、课程管理菜单。在给教师指定课程的时候需要用到课程管理的接口，URL应该是课程管理提供的。
如果只把教师管理分给某个角色，那么在使用教师管理功能时，前端调用课程管理的接口可以通过权限验证吗？

**Comment by lenve** [comment]
你这个设计权限验证肯定通不过。
