### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by TomeC** [lenve/vhr#124]
`ERROR  Failed to compile with 41 errors                                                                          9:49:05 AM

 error  in ./src/App.vue?vue&type=style&index=0&lang=css&

Module parse failed: Unexpected character '#' (14:0)
You may need an appropriate loader to handle this file type.
| 
| 
| #app {
|   font-family: 'Avenir', Helvetica, Arial, sans-serif;
|   -webkit-font-smoothing: antialiased;

 @ ./src/App.vue 4:0-63
 @ ./src/main.js`
好像是npm版本的问题，应该用哪个版本？

**Comment by 857681664** [comment]
我用的npm 6.9.0可以正常启动，你可以用这个版本试试

**Comment by balalalaomoxian** [comment]
你npm i了没

**Comment by TomeC** [comment]
是npm版本的问题
