### ISSUE TITLE
哪一位大佬知道这个项目vue前端如何配置跨域吗？

### ISSUE THREAD

**Issue by chenmingyu0903** [lenve/vhr#129]
哪一位大佬知道这个项目vue前端如何配置跨域吗？proxyTable打包后就无效了，直接修改访问地址，登录会一瞬间失效。

**Comment by 857681664** [comment]
可以描述一下哪里出了跨域错误吗

**Comment by chenmingyu0903** [comment]
你好，主要是直接用http://127.0.0.1:8082/xxx/xxxx去访问好像登录上去无效，请问这是为什么呢？其他跨域的话解决了。

**Comment by lenve** [comment]
项目打包部署的时候可以放在相同的域下，就不必跨域了

**Comment by whxmm0608** [comment]
后端返回的header设置允许跨域
