### ISSUE TITLE
windows编译问题

### ISSUE THREAD

**Issue by rrbaby** [lenve/vhr#14]
您好，我用windows系统vue run dev后， depMana.vue会报uncpect synatic异常在181行，mac系统下就没这问题，请问你在开发的时候有遇到过这问题么

**Comment by lenve** [comment]
这个是由于你两个系统对JSX语法的配置不同导致的。DepMana第181行这里涉及到了JSX语法。

**Comment by rrbaby** [comment]
多谢哈~了解了
