### ISSUE TITLE
文字变乱码

### ISSUE THREAD

**Issue by ozzil** [lenve/vhr#164]
application properties文件在VSCode里打开后注释变乱码，设置Guess Encoding后边成俄文了。。。。

**Comment by ozzil** [comment]
已经解决，用zip下载的方式导入本地工作区后，GB18030奏效

**Comment by netyangs** [comment]
打开中文乱码的 是因为有些文档是GBK写的，用VScode 选择重新编码打开 即可

**Comment by ozzil** [comment]
我的更棘手一点，因为是日文系统，重新编码不起作用。。
