### ISSUE TITLE
所属部门下拉菜单会同时出现左右两个一样的下拉菜单，如图

### ISSUE THREAD

**Issue by XOS** [lenve/vhr#178]
<img width="1374" alt="截屏2020-01-0621 36 16" src="https://user-images.githubusercontent.com/22255253/71821383-fc258380-30cc-11ea-935c-0689029f354f.png">

**Comment by AlexYY0** [comment]
兄弟解决了吗  不仅如此   我的部门树还在  但是名字是空白  无法显示
