### ISSUE TITLE
登录没有反应

### ISSUE THREAD

**Issue by jihan513** [lenve/vhr#19]
你好 我根据你的步骤把项目部署到本地 打开http://localhost:8082/index.html 输入账号密码点登录 然后一直在转圈 请问这是怎么回事

**Comment by YuHangZM** [comment]
作者从来不回复，你的mysql 的数据库账号 ，密码是对的么？

**Comment by best666** [comment]
这是没连接上你的数据库，如楼上说的。修改mysql数据库配置文件里面的密码就可以了。
