### ISSUE TITLE
是不是存在很多功能没有完成 我看很多页面是处于空置的状态

### ISSUE THREAD

**Issue by Zzih** [lenve/vhr#263]
![image](https://user-images.githubusercontent.com/33439363/105841195-34b53980-600f-11eb-894c-0749aa58e2f7.png)
![image](https://user-images.githubusercontent.com/33439363/105841208-3aab1a80-600f-11eb-8a85-db932c96512f.png)

**Comment by BitHachi** [comment]
我也很好奇

**Comment by LynnLLY** [comment]
同样

**Comment by WuJingLearn** [comment]
都是crud，入门一下就好了
