### ISSUE TITLE
调试出现跨域问题怎么解决

### ISSUE THREAD

**Issue by 15116339234** [lenve/vhr#27]

**Comment by lenve** [comment]
请参考前端源码，配置数据转发即可

**Comment by 15116339234** [comment]
No 'Access-Control-Allow-Origin'  前端出现这个原因我在onAuthenticationFailure中httpServletResponse.setHeader("Access-Control-Allow-Origin", "*");加了这个登录之后就没问题，但是其他的接口还是会出现跨域问题
