### ISSUE TITLE
建议提高 Java 技术代码量、降低耦合度

### ISSUE THREAD

**Issue by aBananaWolf** [lenve/vhr#281]
建议分布式集群化，新增 并发会话控制，新增 短信验证码 登录功能，并使用 BeanPostProcessor 和 ImportBeanDefinitionRegistrar，统一登录校验流程，发送邮件部分建议采用 elastic-job 分布式定时任务保证消息投递的可靠性，使用 雪花 id 作为 correctionId，mysql 中使用状态字段保证消息消费的幂等性，项目进行全局异常处理和错误页面处理

**Comment by chenjia123** [comment]
Instead of ISSUE, use PR.
