### ISSUE TITLE
请问前端请求我的那个菜单栏时为什么是302，是要做什么操作嘛

### ISSUE THREAD

**Issue by 15116339234** [lenve/vhr#29]

**Comment by 15116339234** [comment]
是因为cookie,没有登录信息所以跳转到login_p中去了？

**Comment by lenve** [comment]
是的，菜单接口要登录才能调用

**Comment by 15116339234** [comment]
你是用store保存信息的，还有什么方法可以保存信息吗？主要是不知道这个cookie是怎么传到我后台来的

**Comment by 15116339234** [comment]
你那个cookie是怎么传的

**Comment by lenve** [comment]
没有手动传，使用了SpringSecurity的默认配置。

**Comment by 15116339234** [comment]
但是我调试的时候前端说得不到我的那个Set-cookie，然后它请求接口的时候没带我的返回给他的那个cookie，所以总是302，在后台是匿名登录，所以一直想不通为什么前端cookie怎么不传过来
