### ISSUE TITLE
访问目录问题

### ISSUE THREAD

**Issue by kangxiaojun** [lenve/vhr#59]
![image](https://user-images.githubusercontent.com/25812776/47898409-b8bffb80-deb0-11e8-838a-6ab355d220bb.png)
![image](https://user-images.githubusercontent.com/25812776/47898475-fd4b9700-deb0-11e8-8403-cde789c56b8f.png)
![image](https://user-images.githubusercontent.com/25812776/47898503-19e7cf00-deb1-11e8-8270-51d677dfb20f.png)
![image](https://user-images.githubusercontent.com/25812776/47898551-574c5c80-deb1-11e8-8421-6d6db11b850b.png)

在后端加上一个访问目录，同时修改前端的访问目录，修改后可以登录，但是在调用“/config/sysmenu"接口加载菜单的时候又成了未登录状态，请问是怎么回事？

**Comment by lenve** [comment]
修改了访问目录，前段所有的访问地址都要修改。在api.js中修改
