### ISSUE TITLE
java代码怎么运行就出错

### ISSUE THREAD

**Issue by yespie** [lenve/vhr#70]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-01-22 00:12:14.325 ERROR 3396 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method redisTemplate in org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration required a bean of type 'org.springframework.data.redis.connection.RedisConnectionFactory' that could not be found.
	- Bean method 'redisConnectionFactory' not loaded because @ConditionalOnClass did not find required class 'redis.clients.jedis.Jedis'
	- Bean method 'redisConnectionFactory' not loaded because @ConditionalOnClass did not find required class 'io.lettuce.core.RedisClient'

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.data.redis.connection.RedisConnectionFactory' in your configuration.

**Comment by lenve** [comment]
参考https://github.com/lenve/vhr/issues/72
