### ISSUE TITLE
STS里，更新了Maven后，运行HrserverApplication.java出现这个异常，请问怎么解决

### ISSUE THREAD

**Issue by yespie** [lenve/vhr#72]
2019-01-24 00:58:31.028  INFO 13104 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'clientInboundChannelExecutor'
2019-01-24 00:58:31.051  INFO 13104 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-01-24 00:58:31.229 ERROR 13104 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method redisTemplate in org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration required a bean of type 'org.springframework.data.redis.connection.RedisConnectionFactory' that could not be found.
	- Bean method 'redisConnectionFactory' not loaded because @ConditionalOnClass did not find required class 'redis.clients.jedis.Jedis'
	- Bean method 'redisConnectionFactory' not loaded because @ConditionalOnClass did not find required class 'io.lettuce.core.RedisClient'

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.data.redis.connection.RedisConnectionFactory' in your configuration.

**Comment by muggle0** [comment]
你应该是redis配置错误了，百度springboot redis配置使用可解决你的问题

**Comment by lenve** [comment]
是的，redis配置错误，启动redis后，修改下application.properties中redis相关的配置即可
