### ISSUE TITLE
请问一下只启动后端的项目和前后端都启动有什么区别

### ISSUE THREAD

**Issue by DeliciousDr** [lenve/vhr#82]
下载完项目后，启动后端的界面和启动前端的界面都一样啊，如果是前后端分离，只启动后端应该只提供接口数据，不能看到界面才对啊，请教这是怎么回事

**Comment by yangmeiooo** [comment]
他把前端打包好了，也放入后端项目里了。你只打开后端项目当然也能看见前端的页面

**Comment by lenve** [comment]
楼上说的没错。
