### ISSUE TITLE
前端如何加文本框前的文字

### ISSUE THREAD

**Issue by Mrssqin** [lenve/vhr#85]
`<el-form-item prop="account">
      账号：<el-input type="text" v-model="loginForm.username"
                auto-complete="off" placeholder="账号"></el-input>
    </el-form-item>`
预期结果应该是账号在文本框前啊 
为啥在文本框上表面那
<img width="296" alt="捕获" src="https://user-images.githubusercontent.com/38006903/56786694-71497500-682c-11e9-837c-1debc656670b.PNG">

**Comment by w306026355** [comment]
@Mrssqin 
<el-form-item label="活动名称">
    <el-input v-model="form.name"></el-input>
</el-form-item> 
填写label即可 多看官方文档提升更快

**Comment by w306026355** [comment]
```
<el-form-item label="活动名称">
    <el-input v-model="form.name"></el-input>
</el-form-item> 
```

**Comment by Mrssqin** [comment]
> ```
> <el-form-item label="活动名称">
>     <el-input v-model="form.name"></el-input>
> </el-form-item> 
> ```
