### ISSUE TITLE
请教一下前端是如何连接后端代码的，在哪里有详细的配置？

### ISSUE THREAD

**Issue by Pony9527** [lenve/vhr#88]
整个项目跑起来了，但是不明白前端和后端分离后是如何做到的。

**Comment by w306026355** [comment]
@Pony9527 前端通过ajax请求后端controller层，controller层返回json数据，前端拿到json数据解析，这就是前后端分离。

**Comment by Pony9527** [comment]
早哇！这个请求我理解，不过我不明白的是假如我现在有两个项目都有一样的Controller  URL，前段是如何进行区分的呀？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 她爱微笑 <notifications@github.com>
发送时间: 2019年5月6日 08:38
收件人: lenve/vhr <vhr@noreply.github.com>
抄送: SuperPony_ <1269549217@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[lenve/vhr] 请教一下前端是如何连接后端代码的，在哪里有详细的配置？ (#88)

**Comment by w306026355** [comment]
@Pony9527 你两个项目启动的端口肯定不一样啊，url通过端口已经区分开了啊

**Comment by Pony9527** [comment]
@w306026355 Thank you! I got it.
