### ISSUE TITLE
兄弟，登录的时候密码多少啊

### ISSUE THREAD

**Issue by xuepuhao** [lenve/vhr#90]

**Comment by maxwell0811** [comment]
123

**Comment by xuepuhao** [comment]
老哥，有一个小问题想问一下，如果新增了一个页面，系统管理员想查看的话，好像只能去数据库更改权限

**Comment by RingoDu** [comment]
admin 密码123登陆失败啊

**Comment by lenve** [comment]
> admin 密码123登陆失败啊，“账户名或者密码输入错误”。。。

可能是你数据库连接信息不对吧

**Comment by lenve** [comment]
> 老哥，有一个小问题想问一下，如果新增了一个页面，系统管理员想查看的话，好像只能去数据库更改权限

是这样的
