### ISSUE TITLE
security拦截后怎么重定向到登录界面

### ISSUE THREAD

**Issue by Jiangzehang** [lenve/vhr#95]

**Comment by DavidCalls** [comment]
.formLogin().loginPage("/index.html").loginProcessingUrl("/login")

**Comment by lenve** [comment]
> .formLogin().loginPage("/index.html").loginProcessingUrl("/login")

是的，这样可以实现功能。

不过前后端分离后，需要重定向的话，建议由后端返回json，前端根据json内容通过路由来做页面跳转。
