### ISSUE TITLE
你好，服务器是挂了吗？本地连不上

### ISSUE THREAD

**Issue by 18876293672** [lenve/vhr#97]
<img width="1298" alt="屏幕快照 2019-06-22 23 12 32" src="https://user-images.githubusercontent.com/48558210/59965628-5d2ba680-9543-11e9-927f-6e9caa673ae9.png">我刚拉下的代码，链接不上

**Comment by w306026355** [comment]
改成你自己的数据库地址和密码

**Comment by lenve** [comment]
> 改成你自己的数据库地址和密码

是的，修改数据库配置为自己的数据库信息
